### ISSUE TITLE
The whole javax.crypto package is marked as new

### ISSUE THREAD

**Issue by bendem** [gunnarmorling/jdkapidiff#1]
It seems like javax.crypto couldn't be found in java 8 and is thus marked as new in java 9. Would be great if we could see the API differences in there too.

Thanks for your time, it saved a lot of mine.

**Comment by gunnarmorling** [comment]
Hi, glad to hear you find the tool useful and thanks for opening this issue. I vaguely remember some issues around crypto, but kinda forgot the details.

Maybe you'd like to explore it? The starting point would be to add a reference to the Java 8 JAR in the [ModuleRepackager](https://github.com/gunnarmorling/jdkapidiff/blob/master/src/main/java/de/gunnarmorling/jdkapidiff/ModuleRepackager.java#L93) class.

**Comment by gunnarmorling** [comment]
That's fixed now, I've also updated the published report. The only difference in `javax.crypto.*` is a [removed finalizer](https://gunnarmorling.github.io/jdkapidiff/jdk8-jdk9-api-diff.html#javax.crypto.ExemptionMechanism).

**Comment by bendem** [comment]
thanks!
